changes

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -14,19 +14,15 @@ version:
     - apt-get install git -y
     - BUILD_VERSION=$(git describe --tags) || true
     - echo BUILD_VERSION=${BUILD_VERSION:-"0.0.0-${CI_COMMIT_SHORT_SHA}"}
+    - BUILD_VERSION=`echo $BUILD_VERSION | cut -c-17`
+    - SDK_VERSION="Sdk-Ris-PHP-"${BUILD_VERSION}
+    - echo ${SDK_VERSION}
     - |
-      if [ "${BUILD_VERSION:-"0.0.0-${CI_COMMIT_SHORT_SHA}"}" != "" ]
+      if [ "$(grep -q 'SDK_VERSION=${SDK_VERSION}' src/settings.ini)" != "0" ]
       then
-        echo "true"
-        git checkout main
-        sed -i -e 's/SDK_VERSION=0.0.0/SDK_VERSION=\"test-sample-PHP-0710-${BUILD_VERSION}\"/g' settings.ini
-        cat settings.ini
-        git config --global user.email "vishalakshi.v1234@gmail.com"
-        git config --global user.name "Vishalakshi Vishu"
-        git status
-        git add settings.ini
-        git commit -m "updated sdk version"
-        git push https://vishalakshi.v1234:glpat-KT5Mgyd-6e4aGyhCM6xL@gitlab.com/test-group838/test_sample_php_app.git HEAD:main
+        echo "'SDK_VERSION=${SDK_VERSION}' not found"
+        echo "Change SDK_VERSION to 'Sdk-Ris-PHP-next_expected_tag' in src/settings.ini"
+        exit 1
       fi
 
 build:
